[package]
name = "mltg"
version = "0.0.1"
authors = ["LNSEAB <691752+LNSEAB@users.noreply.github.com>"]
edition = "2018"

[dependencies]
gecl = "0.0.1"
windows = "0.10.0"

[build-dependencies]
windows = "0.10.0"

[dev-dependencies]
anyhow = "1.0.40"
wita = "0.10.0"
