[package]
name = "mltg_bindings"
version = "0.2.2"
authors = ["LNSEAB <691752+LNSEAB@users.noreply.github.com>"]
edition = "2018"
license = "MIT"
description = "windows bindings for mltg"

[dependencies]
windows = "0.21.1"

[build-dependencies]
windows = "0.21.1"
